//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinancialReportApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings_InputHandling {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_InputHandling() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FinancialReportApp.Resources.Strings.InputHandling", typeof(Strings_InputHandling).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input. Please enter a valid decimal number..
        /// </summary>
        internal static string PromptDecimal_Invalid {
            get {
                return ResourceManager.GetString("PromptDecimal_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input must be between {0} and {1}. Please enter a valid decimal number..
        /// </summary>
        internal static string PromptDecimal_OutOfBounds {
            get {
                return ResourceManager.GetString("PromptDecimal_OutOfBounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input. Please select a valid option..
        /// </summary>
        internal static string PromptEnum_Invalid {
            get {
                return ResourceManager.GetString("PromptEnum_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an option: .
        /// </summary>
        internal static string PromptEnum_Option {
            get {
                return ResourceManager.GetString("PromptEnum_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an option: .
        /// </summary>
        internal static string PromptEnum_Option1 {
            get {
                return ResourceManager.GetString("PromptEnum_Option1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input. Please enter a valid integer..
        /// </summary>
        internal static string PromptInt_Invalid {
            get {
                return ResourceManager.GetString("PromptInt_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input cannot be empty. Please enter a valid string..
        /// </summary>
        internal static string PromptString_Invalid {
            get {
                return ResourceManager.GetString("PromptString_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input cannot be empty. Please enter a valid string..
        /// </summary>
        internal static string PromptString_Invalid1 {
            get {
                return ResourceManager.GetString("PromptString_Invalid1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input. Please enter &apos;y&apos; or &apos;n&apos;..
        /// </summary>
        internal static string PromptYesNo_Invalid {
            get {
                return ResourceManager.GetString("PromptYesNo_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to n, no.
        /// </summary>
        internal static string PromptYesNo_NoInputs {
            get {
                return ResourceManager.GetString("PromptYesNo_NoInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (y/n): .
        /// </summary>
        internal static string PromptYesNo_QuestionSuffix {
            get {
                return ResourceManager.GetString("PromptYesNo_QuestionSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y, yes.
        /// </summary>
        internal static string PromptYesNo_YesInputs {
            get {
                return ResourceManager.GetString("PromptYesNo_YesInputs", resourceCulture);
            }
        }
    }
}
