//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinancialReportApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FinancialReportApp.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear custom tax brackets..
        /// </summary>
        internal static string ClearCustomTaxUI_MenuAttribute {
            get {
                return ResourceManager.GetString("ClearCustomTaxUI_MenuAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear operation cancelled..
        /// </summary>
        internal static string ClearCustomTaxUI_Message_Cancelled {
            get {
                return ResourceManager.GetString("ClearCustomTaxUI_Message_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom tax brackets cleared..
        /// </summary>
        internal static string ClearCustomTaxUI_Message_Cleared {
            get {
                return ResourceManager.GetString("ClearCustomTaxUI_Message_Cleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to clear all custom tax brackets?.
        /// </summary>
        internal static string ClearCustomTaxUI_Prompt {
            get {
                return ResourceManager.GetString("ClearCustomTaxUI_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear tax credits..
        /// </summary>
        internal static string ClearTaxCreditsUI_MenuAttribute {
            get {
                return ResourceManager.GetString("ClearTaxCreditsUI_MenuAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax credits not cleared..
        /// </summary>
        internal static string ClearTaxCreditsUI_Message_Cancelled {
            get {
                return ResourceManager.GetString("ClearTaxCreditsUI_Message_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All tax credits cleared..
        /// </summary>
        internal static string ClearTaxCreditsUI_Message_Cleared {
            get {
                return ResourceManager.GetString("ClearTaxCreditsUI_Message_Cleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to clear all tax credits?.
        /// </summary>
        internal static string ClearTaxCreditsUI_Prompt {
            get {
                return ResourceManager.GetString("ClearTaxCreditsUI_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input custom tax brackets..
        /// </summary>
        internal static string InputCustomTaxMenu_Menu {
            get {
                return ResourceManager.GetString("InputCustomTaxMenu_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Custom Tax Brackets Menu..
        /// </summary>
        internal static string InputCustomTaxMenu_Message_Start {
            get {
                return ResourceManager.GetString("InputCustomTaxMenu_Message_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input custom tax brackets..
        /// </summary>
        internal static string InputCustomTaxUI_Menu {
            get {
                return ResourceManager.GetString("InputCustomTaxUI_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last tax bracket has no upper limit. Unable to add more brackets..
        /// </summary>
        internal static string InputCustomTaxUI_Message_End {
            get {
                return ResourceManager.GetString("InputCustomTaxUI_Message_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Tax Bracket starting point: {0}.
        /// </summary>
        internal static string InputCustomTaxUI_Message_Lower {
            get {
                return ResourceManager.GetString("InputCustomTaxUI_Message_Lower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter tax rate (as a percentage): .
        /// </summary>
        internal static string InputCustomTaxUI_Message_Rate {
            get {
                return ResourceManager.GetString("InputCustomTaxUI_Message_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter upper boundary (or leave blank for no upper limit): .
        /// </summary>
        internal static string InputCustomTaxUI_Message_Upper {
            get {
                return ResourceManager.GetString("InputCustomTaxUI_Message_Upper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input expense item..
        /// </summary>
        internal static string InputExpenseItem_Menu {
            get {
                return ResourceManager.GetString("InputExpenseItem_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter expense amount: .
        /// </summary>
        internal static string InputExpenseItem_Prompt_Amount {
            get {
                return ResourceManager.GetString("InputExpenseItem_Prompt_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter expense category: .
        /// </summary>
        internal static string InputExpenseItem_Prompt_Category {
            get {
                return ResourceManager.GetString("InputExpenseItem_Prompt_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter expense frequency (e.g., Monthly, Weekly): .
        /// </summary>
        internal static string InputExpenseItem_Prompt_Frequency {
            get {
                return ResourceManager.GetString("InputExpenseItem_Prompt_Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input expenses..
        /// </summary>
        internal static string InputExpensesMenu_Menu {
            get {
                return ResourceManager.GetString("InputExpensesMenu_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Expenses Menu - Please select an option:.
        /// </summary>
        internal static string InputExpensesMenu_Message_Start {
            get {
                return ResourceManager.GetString("InputExpensesMenu_Message_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Salary..
        /// </summary>
        internal static string InputSalaryMenu_Menu {
            get {
                return ResourceManager.GetString("InputSalaryMenu_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Salary Menu - Please select an option:.
        /// </summary>
        internal static string InputSalaryMenu_Message_Start {
            get {
                return ResourceManager.GetString("InputSalaryMenu_Message_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input tax credits..
        /// </summary>
        internal static string InputTaxCreditUI_Menu {
            get {
                return ResourceManager.GetString("InputTaxCreditUI_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input tax credit/deductible: .
        /// </summary>
        internal static string InputTaxCreditUI_Prompt_Amount {
            get {
                return ResourceManager.GetString("InputTaxCreditUI_Prompt_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main menu.
        /// </summary>
        internal static string MainMenu_Menu {
            get {
                return ResourceManager.GetString("MainMenu_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option: .
        /// </summary>
        internal static string MainMenu_Message_End {
            get {
                return ResourceManager.GetString("MainMenu_Message_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid option number..
        /// </summary>
        internal static string MainMenu_Message_Error {
            get {
                return ResourceManager.GetString("MainMenu_Message_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an option:.
        /// </summary>
        internal static string MainMenu_Message_Start {
            get {
                return ResourceManager.GetString("MainMenu_Message_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back..
        /// </summary>
        internal static string Menu_Message_Back {
            get {
                return ResourceManager.GetString("Menu_Message_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option: .
        /// </summary>
        internal static string Menu_Message_End {
            get {
                return ResourceManager.GetString("Menu_Message_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid option number..
        /// </summary>
        internal static string Menu_Message_Error {
            get {
                return ResourceManager.GetString("Menu_Message_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit..
        /// </summary>
        internal static string Menu_Message_Exit {
            get {
                return ResourceManager.GetString("Menu_Message_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}. {1}.
        /// </summary>
        internal static string Menu_Message_MenuOption {
            get {
                return ResourceManager.GetString("Menu_Message_MenuOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an option:.
        /// </summary>
        internal static string Menu_Message_Start {
            get {
                return ResourceManager.GetString("Menu_Message_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove expense item.
        /// </summary>
        internal static string RemoveExpenseItemUI_Menu {
            get {
                return ResourceManager.GetString("RemoveExpenseItemUI_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Expenses:.
        /// </summary>
        internal static string RemoveExpenseItemUI_Message_Current {
            get {
                return ResourceManager.GetString("RemoveExpenseItemUI_Message_Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid index..
        /// </summary>
        internal static string RemoveExpenseItemUI_Message_Invalid {
            get {
                return ResourceManager.GetString("RemoveExpenseItemUI_Message_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No expenses to remove..
        /// </summary>
        internal static string RemoveExpenseItemUI_Message_Nothing {
            get {
                return ResourceManager.GetString("RemoveExpenseItemUI_Message_Nothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense removed..
        /// </summary>
        internal static string RemoveExpenseItemUI_Message_Removed {
            get {
                return ResourceManager.GetString("RemoveExpenseItemUI_Message_Removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the number of the expense to remove: .
        /// </summary>
        internal static string RemoveExpenseItemUI_Prompt_Number {
            get {
                return ResourceManager.GetString("RemoveExpenseItemUI_Prompt_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove tax credit.
        /// </summary>
        internal static string RemoveTaxCreditUI_Menu {
            get {
                return ResourceManager.GetString("RemoveTaxCreditUI_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current credits:.
        /// </summary>
        internal static string RemoveTaxCreditUI_Message_Current {
            get {
                return ResourceManager.GetString("RemoveTaxCreditUI_Message_Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid index..
        /// </summary>
        internal static string RemoveTaxCreditUI_Message_Invalid {
            get {
                return ResourceManager.GetString("RemoveTaxCreditUI_Message_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No credits to remove..
        /// </summary>
        internal static string RemoveTaxCreditUI_Message_Nothing {
            get {
                return ResourceManager.GetString("RemoveTaxCreditUI_Message_Nothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit removed..
        /// </summary>
        internal static string RemoveTaxCreditUI_Message_Removed {
            get {
                return ResourceManager.GetString("RemoveTaxCreditUI_Message_Removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the number of the credits to remove: .
        /// </summary>
        internal static string RemoveTaxCreditUI_Prompt_Number {
            get {
                return ResourceManager.GetString("RemoveTaxCreditUI_Prompt_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Report..
        /// </summary>
        internal static string ReportUI_Menu {
            get {
                return ResourceManager.GetString("ReportUI_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to write report to {0}.
        /// </summary>
        internal static string ReportUI_Message_Failure {
            get {
                return ResourceManager.GetString("ReportUI_Message_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Report written to {0}&quot;.
        /// </summary>
        internal static string ReportUI_Message_Success {
            get {
                return ResourceManager.GetString("ReportUI_Message_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to write the report to a file?.
        /// </summary>
        internal static string ReportUI_Prompt_Write {
            get {
                return ResourceManager.GetString("ReportUI_Prompt_Write", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input salary after tax.
        /// </summary>
        internal static string SalaryAfterTaxUI_Menu {
            get {
                return ResourceManager.GetString("SalaryAfterTaxUI_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your salary after tax: .
        /// </summary>
        internal static string SalaryAfterTaxUI_Message_Salary {
            get {
                return ResourceManager.GetString("SalaryAfterTaxUI_Message_Salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the amount of tax paid: .
        /// </summary>
        internal static string SalaryAfterTaxUI_Message_Tax {
            get {
                return ResourceManager.GetString("SalaryAfterTaxUI_Message_Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input salary before tax..
        /// </summary>
        internal static string SalaryBeforeTaxUI_Menu {
            get {
                return ResourceManager.GetString("SalaryBeforeTaxUI_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your salary before tax: .
        /// </summary>
        internal static string SalaryBeforeTaxUI_Message_Salary {
            get {
                return ResourceManager.GetString("SalaryBeforeTaxUI_Message_Salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Salary Frequency..
        /// </summary>
        internal static string SalaryFrequencyMenu_Menu {
            get {
                return ResourceManager.GetString("SalaryFrequencyMenu_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Salary Frequency:.
        /// </summary>
        internal static string SalaryFrequencyMenu_Message_Start {
            get {
                return ResourceManager.GetString("SalaryFrequencyMenu_Message_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input tax credits..
        /// </summary>
        internal static string TaxCreditMenu_Menu {
            get {
                return ResourceManager.GetString("TaxCreditMenu_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Credit Menu - Please select an option:.
        /// </summary>
        internal static string TaxCreditMenu_Message_Start {
            get {
                return ResourceManager.GetString("TaxCreditMenu_Message_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View custom tax brackets..
        /// </summary>
        internal static string ViewCustomTaxUI_Menu {
            get {
                return ResourceManager.GetString("ViewCustomTaxUI_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range: {0} - {1}. Rate: {2}.
        /// </summary>
        internal static string ViewCustomTaxUI_Message_Bracket {
            get {
                return ResourceManager.GetString("ViewCustomTaxUI_Message_Bracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all expenses..
        /// </summary>
        internal static string ViewExpensesUI_Menu {
            get {
                return ResourceManager.GetString("ViewExpensesUI_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Expenses:.
        /// </summary>
        internal static string ViewExpensesUI_Message_Current {
            get {
                return ResourceManager.GetString("ViewExpensesUI_Message_Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No expenses recorded..
        /// </summary>
        internal static string ViewExpensesUI_Message_Empty {
            get {
                return ResourceManager.GetString("ViewExpensesUI_Message_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1} ({2}).
        /// </summary>
        internal static string ViewExpensesUI_Message_Expense {
            get {
                return ResourceManager.GetString("ViewExpensesUI_Message_Expense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View All Tax Credits..
        /// </summary>
        internal static string ViewTaxCreditsUI_Menu {
            get {
                return ResourceManager.GetString("ViewTaxCreditsUI_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - {0:C}.
        /// </summary>
        internal static string ViewTaxCreditsUI_Message_Credit {
            get {
                return ResourceManager.GetString("ViewTaxCreditsUI_Message_Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Tax Credits: {0:C}.
        /// </summary>
        internal static string ViewTaxCreditsUI_Message_Total {
            get {
                return ResourceManager.GetString("ViewTaxCreditsUI_Message_Total", resourceCulture);
            }
        }
    }
}
